%%{ init: { 'gitGraph': { 'mainBranchName': '... 4 more bosses' } } }%%
gitGraph
	commit id: "Eater of Worlds" type: REVERSE
	commit id: "The Hive Mind" type: REVERSE
  	commit id: "Queen Bee" type: REVERSE
  	commit id: "Skeletron" type: REVERSE
  	commit id: "The Slime God" type: HIGHLIGHT tag: "Currently fighting..."
	commit id: "Wall of Flesh"
	commit id: "Queen Slime"
	commit id: "Aquatic Scourge"
	commit id: "???"
