%%{ init: { 'gitGraph': { 'mainBranchName': 'Calamity' }, 'theme': 'dark', 'themeVariables': { 'background': 'transparent' } } }%%
gitGraph
	commit id: "King Slime" type: REVERSE
	commit id: "Desert Scourge" type: REVERSE
	commit id: "Eye of Cthulhu" type: REVERSE
	commit id: "Crabulon" type: REVERSE
	commit id: "Eater of Worlds" type: REVERSE
	commit id: "The Hive Mind" type: REVERSE
  commit id: "Queen Bee" type: HIGHLIGHT tag: "Currently fighting..."
  commit id: "Skeletron"
  commit id: "The Slime God"
